services:
  db:
    image: postgres
    container_name: tickets_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tickets
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  api:
    image: tickets:latest
    container_name: tickets
    build: .
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_DB=jdbc:postgresql://db:5433/tickets
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=5
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - redis

volumes:
  db-data: