spring:
  application:
    name:tickets
  datasource:
    url: jdbc:postgresql://db:5432/tickets
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/myapp.log
