spring:
  application:
    name: tickets
  cache:
    type: redis
  profiles:
    active: @spring.profiles.active@

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
      show-components: always
  server:
    port: 8080

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351