spring:
  application:
    name:tickets
  datasource:
    url: jdbc:postgresql://db:5432/tickets
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/myapp.log
