spring:
  application:
    name:tickets
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      time-to-live: 60000
  datasource:
    url: jdbc:postgresql://db:5432/tickets
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
